const PEOPLE = ['TJ', 'Emma', 'Macon', 'Chloe', 'Bill', 'Tonya'];
const FAMILY_PASSWORD = 'holly';
const STORAGE_KEY = 'vining-family-christmas-2026';
const LEGACY_STORAGE_KEY = 'vining-family-christmas-2025';
const SESSION_KEY = 'vining-family-christmas-session';
const THEME_KEY = 'vining-family-christmas-theme';
const REVEAL_KEY = 'vining-family-christmas-2026-reveal';
const GIVING_INTRO_KEY = 'vining-family-christmas-2026-giving-intro';
const MY_LIST_INTRO_KEY = 'vining-family-christmas-2026-my-list-intro';
const CHRISTMAS_DATE = new Date(2026,11,25,0,0,0);
const FIREBASE_ROOT = 'viningFamilyChristmas/2026';
const FIREBASE_CONFIG = {apiKey:'AIzaSyDGpfYn1-YMV6jkJn9nDgvk1_yrYydem0U',authDomain:'ski-trip-2027.firebaseapp.com',databaseURL:'https://ski-trip-2027-default-rtdb.firebaseio.com',projectId:'ski-trip-2027',storageBucket:'ski-trip-2027.firebasestorage.app',messagingSenderId:'248692108351',appId:'1:248692108351:web:f65f4b12bbf0987b6bdc8a'};
const STARTER_DATA_VERSION = 1;
const EXAMPLE_ITEM = {
  name:'[EXAMPLE] Tru-Tone Christmas Light Set',
  priority:3,
  link:'https://tru-tone.com/pages/classic-light-set',
  cost:'$29.95+',
  notes:'This is an example item. Delete it once you have started adding your own gift ideas.'
};

let db;
try{db=loadDb();}catch(error){localStorage.removeItem(STORAGE_KEY);db=loadDb();}
let currentUser = localStorage.getItem(SESSION_KEY);
let currentView = 'lists';
let switchingUser = false;
let selectedPerson = null;
let purchaseGiftId = null;
let selectedBuyers = [];
let pendingUnclaim = null;
let pendingProgress = null;
let editItemId = null;
let pendingDelete = null;
let pendingCommentDelete = null;
let pendingFeatureDelete = null;
let editingFeatureId = null;
let loginPerson = PEOPLE[0];
let chatOpen = false;
const CHAT_SEEN_KEY = 'vining-family-christmas-chat-seen';
let firebaseDb = null;
let sharedStateRef = null;
let myPresenceRef = null;

function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem(THEME_KEY,theme);document.querySelectorAll('.theme-toggle').forEach(button=>button.textContent=theme==='light'?'☾':'☼');}
setTheme(localStorage.getItem(THEME_KEY)||'dark');

function starterLists(){const lists={};PEOPLE.forEach(person=>{lists[person]=[{...EXAMPLE_ITEM,id:`${person}-example`,purchased:null}];});return lists;}
function freshDb(){return {lists:starterLists(),featureRequests:[],chatMessages:[],lastLogins:{},starterDataVersion:STARTER_DATA_VERSION};}
function values(value){return Array.isArray(value)?value.filter(Boolean):value&&typeof value==='object'?Object.values(value).filter(Boolean):[];}
function normalizeDb(value){const parsed=value&&typeof value==='object'?JSON.parse(JSON.stringify(value)):freshDb();if(!parsed.lists||typeof parsed.lists!=='object')parsed.lists={};if(parsed.lists.Megan&&!parsed.lists.Macon){parsed.lists.Macon=parsed.lists.Megan;delete parsed.lists.Megan;}if(parsed.lists.Tanya&&!parsed.lists.Tonya){parsed.lists.Tonya=parsed.lists.Tanya;delete parsed.lists.Tanya;}PEOPLE.forEach(person=>{parsed.lists[person]=values(parsed.lists[person]);});parsed.featureRequests=values(parsed.featureRequests);parsed.chatMessages=values(parsed.chatMessages);if(!parsed.lastLogins||typeof parsed.lastLogins!=='object')parsed.lastLogins={};parsed.starterDataVersion=STARTER_DATA_VERSION;return parsed;}
function loadDb(){const current=localStorage.getItem(STORAGE_KEY);const legacy=current?null:localStorage.getItem(LEGACY_STORAGE_KEY);const saved=current||legacy;if(saved){const raw=JSON.parse(saved);const needsStarterReset=raw.starterDataVersion!==STARTER_DATA_VERSION;const parsed=normalizeDb(raw);if(needsStarterReset)parsed.lists=starterLists();localStorage.setItem(STORAGE_KEY,JSON.stringify(parsed));if(legacy)localStorage.removeItem(LEGACY_STORAGE_KEY);return parsed;}return freshDb();}
function cacheDb(nextDb){db=normalizeDb(nextDb);localStorage.setItem(STORAGE_KEY,JSON.stringify(db));}
function refreshSharedViews(){render();renderChat();const featureDialog=document.getElementById('feature-dialog');if(featureDialog?.open)renderFeatureRequests();}
function commitDb(mutator){if(!sharedStateRef){const changed=mutator(db);if(changed===false)return Promise.resolve({committed:false,snapshot:null});cacheDb(db);refreshSharedViews();return Promise.resolve({committed:true,snapshot:null});}return sharedStateRef.transaction(remote=>{const next=normalizeDb(remote||freshDb());if(mutator(next)===false)return;return next;}).catch(error=>{console.error('Firebase update failed',error);return {committed:false,error};});}
function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function dollars(v){return v||'—';}
function numericCost(value){if(typeof value==='number')return Number.isFinite(value)?value:null;const parsed=Number(String(value||'').replace(/[^0-9.-]/g,''));return Number.isFinite(parsed)&&String(value||'').trim()?parsed:null;}
function formatDate(v){if(!v)return '';const date=new Date(`${v}T00:00:00`);return Number.isNaN(date.getTime())?v:date.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}
function stars(n=0){return '★'.repeat(Number(n)||0)+'☆'.repeat(5-(Number(n)||0));}
function total(p){return (db.lists[p]||[]).length;}
function purchasedCount(p){return (db.lists[p]||[]).filter(x=>x.purchased).length;}
function revealAvailable(){return Date.now()>=CHRISTMAS_DATE.getTime();}
function revealActive(){return !!currentUser&&revealAvailable()&&localStorage.getItem(`${REVEAL_KEY}-${currentUser}`)==='true';}
function personMeta(p){return p===currentUser&&!revealActive()?`<strong>${total(p)}</strong> ideas <span>·</span> claims kept secret`:`<strong>${total(p)}</strong> ideas <span>·</span> <strong>${purchasedCount(p)}</strong> claimed`;}

function render(){
  const loginView=document.getElementById('login-view');
  loginView.classList.toggle('hidden',!!currentUser&&!switchingUser);
  loginView.classList.toggle('switching',!!currentUser&&switchingUser);
  document.getElementById('app-view').classList.toggle('hidden',!currentUser);
  document.getElementById('cancel-user-switch').classList.toggle('hidden',!switchingUser);
  if(!currentUser)return;
  renderCountdown();
  renderLoginHistory();
  document.getElementById('current-user-name').textContent=currentUser;
  document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));
  const content=document.getElementById('content');
  if(currentView==='lists') renderLists(content); else if(currentView==='my-list') renderMyList(content); else if(currentView==='person-list') renderPersonList(content); else if(currentView==='giving') renderGiving(content); else renderStatus(content);
}
function renderCountdown(){const el=document.getElementById('christmas-countdown');const now=new Date();const diff=CHRISTMAS_DATE.getTime()-now.getTime();if(diff>0){const days=Math.floor(diff/86400000);const hours=Math.floor(diff%86400000/3600000);const minutes=Math.floor(diff%3600000/60000);el.innerHTML=`<div class="countdown-mark">✦</div><div><span>Christmas 2026</span><strong>${days} days · ${hours} hours · ${minutes} minutes</strong></div><p>until the surprises begin</p>`;}else{const active=revealActive();el.innerHTML=`<div class="countdown-mark">✦</div><div><span>Christmas 2026</span><strong>Merry Christmas!</strong></div><button id="reveal-mode-button" class="reveal-mode-button">${active?'Hide reveal details':'Open year-end reveal'}</button>`;document.getElementById('reveal-mode-button').addEventListener('click',()=>{localStorage.setItem(`${REVEAL_KEY}-${currentUser}`,String(!active));render();});}}
function renderLists(el){
  el.innerHTML=`<div class="section-heading"><div><h3>Everyone’s lists</h3><p>A little window into what would make each person smile.</p></div></div><div class="person-grid">${PEOPLE.map(p=>`<article class="person-card" data-person="${p}"><div class="person-initial">${p[0]}</div><h4>${p}'s list</h4><p>${p===currentUser?'Your list · only you can edit':'Gift ideas, ranked by want'}</p><div class="card-rule"></div><div class="person-meta">${personMeta(p)}</div></article>`).join('')}</div><div class="notice">✦ Other people’s lists show claim details. Your own list keeps those details private from you.</div>${recentUpdatesMarkup()}`;
  el.querySelectorAll('.person-card').forEach(card=>card.addEventListener('click',()=>{selectedPerson=card.dataset.person;currentView=selectedPerson===currentUser?'my-list':'person-list';render();}));
}
function recentUpdatesMarkup(){const updates=PEOPLE.flatMap(person=>(db.lists[person]||[]).filter(item=>item.createdAt).map(item=>({...item,person}))).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,10);return `<section class="updates-section"><div class="section-heading"><div><p class="eyebrow">JUST ADDED</p><h3>Recent updates</h3><p>New ideas making their way onto the family lists.</p></div><span class="updates-live">● LIVE</span></div><div class="updates-ticker">${updates.length?updates.map(item=>`<button class="update-item" data-update-person="${item.person}"><span class="update-dot">✦</span><span><strong>${esc(item.person)}</strong> added <b>${esc(item.name)}</b></span><time>${relativeTime(item.createdAt)}</time></button>`).join(''):'<div class="empty-updates">New additions will appear here as family members update their lists.</div>'}</div></section>`;}
function relativeTime(value){const diff=Math.max(0,Date.now()-new Date(value).getTime());const minutes=Math.floor(diff/60000);if(minutes<1)return 'just now';if(minutes<60)return `${minutes}m ago`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours}h ago`;return `${Math.floor(hours/24)}d ago`;}
function loginTime(value){if(!value)return 'not yet';const date=new Date(value);if(Number.isNaN(date.getTime()))return 'not yet';return date.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
function renderLoginHistory(){const panel=document.getElementById('login-history-panel');if(!panel)return;panel.innerHTML=`<div class="login-history-header"><span class="eyebrow">FAMILY ACTIVITY</span><button type="button" id="close-login-history" aria-label="Close family activity">×</button></div><h3>Last login</h3><div class="login-history-list">${PEOPLE.map(person=>`<div class="login-history-row"><span class="login-history-avatar">${esc(person[0])}</span><strong>${esc(person)}</strong><span>${db.lastLogins?.[person]?`last logged in ${esc(loginTime(db.lastLogins[person]))}`:'not yet logged in'}</span></div>`).join('')}</div>`;document.getElementById('close-login-history')?.addEventListener('click',closeLoginHistory);}
function closeLoginHistory(){const panel=document.getElementById('login-history-panel');const widget=document.getElementById('presence-widget');panel?.classList.add('hidden');widget?.setAttribute('aria-expanded','false');}
function getChatSeen(){return Number(localStorage.getItem(CHAT_SEEN_KEY)||0);}
function renderChat(){const container=document.getElementById('chat-messages');const messages=db.chatMessages||[];container.innerHTML=messages.length?messages.map(message=>`<div class="chat-message ${message.by===currentUser?'mine':''}">${message.by===currentUser?'':`<span class="chat-avatar">${esc(message.by[0])}</span>`}<div><p>${message.by===currentUser?'':`<strong>${esc(message.by)}</strong>`}<time>${relativeTime(message.createdAt)}</time></p><div class="chat-bubble">${esc(message.text)}</div></div></div>`).join(''):'<div class="chat-empty"><span>✦</span><p>No messages yet.<br />Start the family conversation.</p></div>';if(chatOpen&&messages.length)localStorage.setItem(CHAT_SEEN_KEY,String(new Date(messages[messages.length-1].createdAt).getTime()));const unread=messages.filter(message=>message.by!==currentUser&&new Date(message.createdAt).getTime()>getChatSeen()).length;const badge=document.getElementById('chat-badge');badge.textContent=unread>9?'9+':String(unread);badge.classList.toggle('hidden',chatOpen||!unread);requestAnimationFrame(()=>{container.scrollTop=container.scrollHeight;});}
function presenceKey(name){return String(name||'').toLowerCase().replace(/[^a-z0-9_-]/g,'-');}
function registerPresence(){if(!firebaseDb||!currentUser)return;if(myPresenceRef)myPresenceRef.remove();myPresenceRef=firebaseDb.ref(`${FIREBASE_ROOT}/presence/${presenceKey(currentUser)}`);myPresenceRef.onDisconnect().remove();myPresenceRef.set({name:currentUser,initial:currentUser[0],timestamp:firebase.database.ServerValue.TIMESTAMP});}
function renderPresence(presenceMap){const widget=document.getElementById('presence-widget');if(!widget)return;const people=Object.keys(presenceMap||{}).map(key=>({key,...presenceMap[key]}));const avatars=people.slice(0,6).map(person=>`<span class="presence-avatar" title="${esc(person.name)}">${esc(person.initial||person.name[0])}</span>`).join('');let label;if(people.length===1)label=people[0].name===currentUser?'just you, right now':`${people[0].name} is around`;else if(people.length>1)label=`${people.length} around right now`;else label='See family activity';widget.innerHTML=`<span class="presence-dot"></span><span class="presence-avatars">${avatars}</span><span class="presence-label">${esc(label)}</span>`;widget.classList.toggle('hidden',!currentUser);}
function setupFirebase(){if(!window.firebase)return;try{if(!firebase.apps.length)firebase.initializeApp(FIREBASE_CONFIG);firebaseDb=firebase.database();sharedStateRef=firebaseDb.ref(`${FIREBASE_ROOT}/data`);sharedStateRef.on('value',snapshot=>{if(!snapshot.exists())return;cacheDb(snapshot.val());refreshSharedViews();});sharedStateRef.transaction(remote=>remote||freshDb()).catch(error=>console.error('Firebase initialization failed',error));firebaseDb.ref('.info/connected').on('value',snapshot=>{if(snapshot.val()===true)registerPresence();});firebaseDb.ref(`${FIREBASE_ROOT}/presence`).on('value',snapshot=>renderPresence(snapshot.val()||{}));}catch(error){console.error('Firebase setup failed',error);sharedStateRef=null;firebaseDb=null;document.getElementById('presence-widget').classList.add('hidden');}}
function previewMarkup(item){return item.link?`<div class="preview-wrap"><img class="gift-preview" data-preview-url="${esc(item.link)}" alt="" /><span class="preview-fallback">✦</span></div>`:`<div class="preview-wrap"><span class="preview-fallback">✦</span></div>`;}
function commentMarkup(item,person,readOnly=false){const comments=item.comments||[];if(readOnly&&!comments.length)return'';return `<div class="item-comments">${comments.map(comment=>`<div class="comment" data-comment-id="${comment.id}"><span class="comment-avatar">${esc(comment.by[0])}</span><div class="comment-content"><div class="comment-display"><strong>${esc(comment.by)}</strong><p>${esc(comment.text)}</p><time>${relativeTime(comment.createdAt)}${comment.editedAt?' · edited':''}</time>${!readOnly&&comment.by===currentUser?`<span class="comment-actions"><button type="button" data-edit-comment="${comment.id}">Edit</button><button type="button" data-delete-comment="${comment.id}" data-comment-item="${item.id}" data-comment-person="${person}">Delete</button></span>`:''}</div>${!readOnly&&comment.by===currentUser?`<form class="comment-edit-form hidden" data-edit-comment-form="${comment.id}" data-comment-item="${item.id}" data-comment-person="${person}"><input name="editedComment" value="${esc(comment.text)}" required /><button type="submit">Save</button><button type="button" data-cancel-comment-edit>Cancel</button></form>`:''}</div></div>`).join('')}${readOnly?'':`<button type="button" class="comment-toggle" data-comment-toggle="${item.id}">＋ Comment${comments.length?` <span>${comments.length}</span>`:''}</button><form class="comment-form hidden" data-comment-form="${item.id}" data-comment-person="${person}"><input name="comment" required placeholder="Add a private note for the family…" /><button type="submit">Post</button></form>`}</div>`;}
function progressLabel(status){return({claimed:'Claimed',ordered:'Ordered',shipped:'Shipped',delivered:'Delivered',wrapped:'Wrapped'})[status]||'Claimed';}
function purchasedDetails(item,person,allowControls){const purchase=item.purchased;if(!purchase)return'<span class="reveal-unclaimed">Not claimed</span>';const status=purchase.status||'ordered';const canManage=allowControls&&isMyPurchase(item);return `<span class="progress-badge status-${status}">${progressLabel(status)}</span><br />Purchased by ${esc(purchase.by)}${purchase.date?`<br />Purchased ${esc(formatDate(purchase.date))}`:''}${purchase.arrival?`<br />Arriving: ${esc(purchase.arrival)}`:''}${canManage?`<br /><button data-progress="${item.id}" data-person="${person}">Update progress</button><button class="unclaim-button" data-unclaim="${item.id}" data-person="${person}">Unclaim</button>`:''}`;}
function giftStatusMarkup(item,person,editable){if(editable){const controls=`<div class="owner-actions"><button data-edit-item="${item.id}">Edit</button><button class="delete-item-button" data-delete-item="${item.id}">Delete</button></div>`;return revealActive()?`${controls}<div class="reveal-purchase">${purchasedDetails(item,person,false)}</div>`:controls;}return item.purchased?purchasedDetails(item,person,true):`<button data-buy="${item.id}" data-person="${person}">Claim gift</button>`;}
async function hydratePreviews(root=document){const images=[...root.querySelectorAll('img[data-preview-url]')];await Promise.all(images.map(async img=>{try{const response=await fetch(`https://api.microlink.io?url=${encodeURIComponent(img.dataset.previewUrl)}`);const data=await response.json();const imageUrl=data?.data?.image?.url;if(imageUrl){img.src=imageUrl;img.onload=()=>img.classList.add('loaded');img.onerror=()=>img.remove();}else img.remove();}catch(e){img.remove();}}));}
function listMarkup(person, editable=false){
  const list=[...(db.lists[person]||[])].sort((a,b)=>(b.priority||0)-(a.priority||0)||a.name.localeCompare(b.name));
  if(!list.length)return '<div class="empty-state">No wishes here yet.</div>';
  const priced=list.map(item=>numericCost(item.cost)).filter(value=>value!==null);const total=priced.reduce((sum,value)=>sum+value,0);const coverage=priced.length===list.length?`${list.length} priced item${list.length===1?'':'s'}`:`Based on ${priced.length} of ${list.length} priced items`;
  const markup=`<div class="gift-list">${list.map(item=>`<div class="gift-entry"><div class="gift-row">${previewMarkup(item)}<div class="stars" title="Priority ${item.priority||0}">${stars(item.priority)}</div><div class="gift-name"><a class="gift-link" href="${esc(item.link||'#')}" target="_blank" rel="noopener">${esc(item.name)}</a>${item.notes?`<span class="gift-note">${esc(item.notes)}</span>`:''}</div><div class="gift-cost">${esc(dollars(item.cost))}</div><div class="gift-status ${item.purchased?'purchased':''}">${giftStatusMarkup(item,person,editable)}</div>${item.link?`<a class="external-link" href="${esc(item.link)}" target="_blank" rel="noopener" title="Open shopping link">↗</a>`:'<span></span>'}</div>${editable?(revealActive()?commentMarkup(item,person,true):''):commentMarkup(item,person)}</div>`).join('')}</div><div class="list-total"><div><span>Estimated list total</span><small>${coverage}</small></div><strong>${total.toLocaleString(undefined,{style:'currency',currency:'USD'})}</strong></div>`; setTimeout(()=>hydratePreviews(document),0); return markup;
}
function renderMyList(el){
  const p=currentUser;const notice=revealActive()?'✦ Year-end reveal is open. Purchase details and family comments are now visible.':'♡ Your list is visible to the family. Claim and purchase details are hidden from you.';el.innerHTML=`<div class="section-heading"><div><p class="eyebrow">YOUR WISHES</p><h3>${p}'s list</h3><p>Sorted by priority · only you can edit this list.</p></div><div class="list-heading-actions"><button class="help-button" id="my-list-help" type="button">✦ How it works</button><button class="primary-button add-button" id="add-item">+ Add an item</button></div></div><div class="notice">${notice}</div>${listMarkup(p,true)}`; document.getElementById('add-item').addEventListener('click',openAddItem);document.getElementById('my-list-help').addEventListener('click',()=>showMyListIntro(true));bindOwnerActions(el);showMyListIntro();
}
function showMyListIntro(force=false){if(!currentUser)return;const key=`${MY_LIST_INTRO_KEY}-${currentUser}`;if(!force&&localStorage.getItem(key)==='seen')return;localStorage.setItem(key,'seen');document.getElementById('my-list-intro-dialog').showModal();}
function resetItemDialog(){editItemId=null;document.getElementById('item-form').reset();document.getElementById('item-dialog-eyebrow').textContent='ADD TO YOUR LIST';document.getElementById('item-dialog-title').textContent='A thoughtful little want';document.getElementById('item-submit-button').innerHTML='Add to my list <span>→</span>';}
function openAddItem(){resetItemDialog();document.getElementById('item-dialog').showModal();}
function bindOwnerActions(el){el.querySelectorAll('[data-edit-item]').forEach(button=>button.addEventListener('click',()=>openEditItem(button.dataset.editItem)));el.querySelectorAll('[data-delete-item]').forEach(button=>button.addEventListener('click',()=>openDeleteItem(button.dataset.deleteItem)));}
function openEditItem(id){const item=db.lists[currentUser].find(entry=>entry.id===id);if(!item)return;editItemId=id;document.getElementById('gift-input').value=item.name||'';document.getElementById('priority-input').value=String(item.priority||3);document.getElementById('cost-input').value=item.cost||'';document.getElementById('link-input').value=item.link||'';document.getElementById('notes-input').value=item.notes||'';document.getElementById('item-dialog-eyebrow').textContent='EDIT YOUR LIST';document.getElementById('item-dialog-title').textContent='Update this gift';document.getElementById('item-submit-button').innerHTML='Save changes <span>→</span>';document.getElementById('item-dialog').showModal();}
function openDeleteItem(id){const item=db.lists[currentUser].find(entry=>entry.id===id);if(!item)return;pendingDelete=id;document.getElementById('delete-gift-name').textContent=item.name;document.getElementById('delete-dialog').showModal();}
function bindListActions(el){
  el.querySelectorAll('[data-buy]').forEach(b=>b.addEventListener('click',()=>openPurchase(b.dataset.buy,b.dataset.person)));
  el.querySelectorAll('[data-unclaim]').forEach(b=>b.addEventListener('click',()=>openUnclaim(b.dataset.unclaim,b.dataset.person)));
  el.querySelectorAll('[data-progress]').forEach(b=>b.addEventListener('click',()=>openProgress(b.dataset.progress,b.dataset.person)));
  el.querySelectorAll('[data-comment-toggle]').forEach(button=>button.addEventListener('click',()=>{const form=button.nextElementSibling;form.classList.toggle('hidden');if(!form.classList.contains('hidden'))form.elements.comment.focus();}));
  el.querySelectorAll('[data-comment-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const person=form.dataset.commentPerson;const itemId=form.dataset.commentForm;const input=form.elements.comment;const text=input.value.trim();if(!text)return;const comment={id:`comment-${Date.now()}`,by:currentUser,text,createdAt:new Date().toISOString()};input.value='';commitDb(state=>{const item=state.lists[person]?.find(x=>x.id===itemId);if(!item)return false;if(!item.comments)item.comments=[];item.comments.push(comment);});}));
  el.querySelectorAll('[data-edit-comment]').forEach(button=>button.addEventListener('click',()=>{const comment=button.closest('.comment');comment.querySelector('.comment-display').classList.add('hidden');const form=comment.querySelector('[data-edit-comment-form]');form.classList.remove('hidden');form.elements.editedComment.focus();}));
  el.querySelectorAll('[data-cancel-comment-edit]').forEach(button=>button.addEventListener('click',()=>{const comment=button.closest('.comment');comment.querySelector('.comment-display').classList.remove('hidden');comment.querySelector('.comment-edit-form').classList.add('hidden');}));
  el.querySelectorAll('[data-edit-comment-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const person=form.dataset.commentPerson;const itemId=form.dataset.commentItem;const commentId=form.dataset.editCommentForm;const text=form.elements.editedComment.value.trim();if(!text)return;const editedAt=new Date().toISOString();commitDb(state=>{const item=state.lists[person]?.find(x=>x.id===itemId);const comment=item?.comments?.find(entry=>entry.id===commentId&&entry.by===currentUser);if(!comment)return false;comment.text=text;comment.editedAt=editedAt;});}));
  el.querySelectorAll('[data-delete-comment]').forEach(button=>button.addEventListener('click',()=>{pendingCommentDelete={person:button.dataset.commentPerson,itemId:button.dataset.commentItem,commentId:button.dataset.deleteComment};document.getElementById('comment-delete-dialog').showModal();}));
}
function renderPersonList(el){const p=selectedPerson;el.innerHTML=`<div class="section-heading"><div><p class="eyebrow">FAMILY WISHES</p><h3>${p}'s list</h3><p>Priority, notes, price, links, and what’s still available to claim.</p></div><button class="filter-tabs button" id="back-to-lists">← All lists</button></div>${listMarkup(p,false)}`;document.getElementById('back-to-lists').addEventListener('click',()=>{selectedPerson=null;currentView='lists';render();});bindListActions(el);}
function purchaseBuyers(item){if(!item.purchased)return[];if(Array.isArray(item.purchased.buyerIds)&&item.purchased.buyerIds.length)return item.purchased.buyerIds;if(Array.isArray(item.purchased.buyers)&&item.purchased.buyers.length)return item.purchased.buyers;if(item.purchased.buyerId)return[item.purchased.buyerId];const match=PEOPLE.find(person=>person.toLowerCase()===String(item.purchased.by||'').trim().toLowerCase());return match?[match]:[];}
function isMyPurchase(item){return purchaseBuyers(item).includes(currentUser);}
function myPurchaseShare(item){const cost=numericCost(item.cost);if(cost===null)return null;const buyers=purchaseBuyers(item);return buyers.length?cost/buyers.length:cost;}
function renderGiving(el){const recipients=PEOPLE.filter(person=>person!==currentUser).map(person=>{const claimed=(db.lists[person]||[]).filter(isMyPurchase);const prices=claimed.map(myPurchaseShare);const total=prices.reduce((sum,value)=>sum+(value===null?0:value),0);return {person,claimed,total,missing:prices.filter(value=>value===null).length};});const grandTotal=recipients.reduce((sum,entry)=>sum+entry.total,0);const claimedCount=recipients.reduce((sum,entry)=>sum+entry.claimed.length,0);const average=recipients.length?grandTotal/recipients.length:0;el.innerHTML=`<div class="section-heading giving-heading"><div><p class="eyebrow">YOUR CHRISTMAS GIVING</p><h3>Spending overview</h3><p>Based on listed prices; jointly purchased gifts are split evenly.</p></div><div class="giving-grand-total"><span>Your claimed share</span><strong>${grandTotal.toLocaleString(undefined,{style:'currency',currency:'USD'})}</strong><small>${claimedCount} gift${claimedCount===1?'':'s'} across ${recipients.length} people</small><button class="help-button" id="giving-help" type="button">✦ How it works</button></div></div><div class="notice">◇ Your current average is <strong>${average.toLocaleString(undefined,{style:'currency',currency:'USD'})}</strong> per person. Joint gifts are divided equally among their purchasers.</div><div class="giving-grid">${recipients.map(entry=>givingCard(entry,average)).join('')}</div>`;document.getElementById('giving-help').addEventListener('click',()=>showGivingIntro(true));}
function givingCard(entry,average){const difference=entry.total-average;const comparison=Math.abs(difference)<0.005?'Right at your average':`${Math.abs(difference).toLocaleString(undefined,{style:'currency',currency:'USD'})} ${difference>0?'above':'below'} average`;return `<article class="giving-card"><div class="giving-person"><span>${entry.person[0]}</span><div><h4>${entry.person}</h4><p>${entry.claimed.length} claimed gift${entry.claimed.length===1?'':'s'}</p></div></div><strong class="giving-total">${entry.total.toLocaleString(undefined,{style:'currency',currency:'USD'})}</strong><div class="giving-comparison ${difference>0?'above':difference<0?'below':''}">${comparison}</div>${entry.missing?`<small>Plus ${entry.missing} claimed item${entry.missing===1?'':'s'} without a listed price</small>`:''}</article>`;}
function showGivingIntro(force=false){if(!currentUser)return;const key=`${GIVING_INTRO_KEY}-${currentUser}`;if(!force&&localStorage.getItem(key)==='seen')return;localStorage.setItem(key,'seen');document.getElementById('giving-intro-dialog').showModal();}
function renderStatus(el){
  const people=selectedPerson&&selectedPerson!==currentUser?[selectedPerson]:PEOPLE.filter(p=>p!==currentUser);
  el.innerHTML=`<div class="section-heading"><div><p class="eyebrow">THE SURPRISE DEPARTMENT</p><h3>Status sheets</h3><p>See what’s still available to claim. Your own sheet is kept private.</p></div></div><div class="status-list">${people.map(p=>statusCard(p)).join('')}</div>`;
  bindListActions(el);
}
function statusCard(p){const list=[...(db.lists[p]||[])].sort((a,b)=>(b.priority||0)-(a.priority||0));const claimed=purchasedCount(p);return `<article class="status-card"><h4>${p}'s status</h4><p class="sub">${claimed} of ${list.length} gifts claimed</p><div class="status-progress"><i style="width:${list.length?claimed/list.length*100:0}%"></i></div>${list.map(item=>`<div class="mini-gift"><div><span style="color:var(--ink)">${esc(item.name)}</span><br /><span>${item.cost||'Cost not listed'}</span></div>${item.purchased?`<span class="status-purchased">✓ ${esc(item.purchased.by)}<br />${esc(item.purchased.date||'')}<br /><button class="unclaim-button" data-unclaim="${item.id}" data-person="${p}">Unclaim</button></span>`:`<button data-buy="${item.id}" data-person="${p}">Claim</button>`}</div>`).join('')}</article>`;}

document.getElementById('person-choices').innerHTML=PEOPLE.map((p,i)=>`<button type="button" class="person-choice${i===0?' selected':''}" data-person-choice="${p}"><span>${p[0]}</span>${p}</button>`).join('');
document.querySelectorAll('[data-person-choice]').forEach(button=>button.addEventListener('click',()=>{loginPerson=button.dataset.personChoice;document.querySelectorAll('[data-person-choice]').forEach(choice=>choice.classList.toggle('selected',choice===button));}));
document.getElementById('login-form').addEventListener('submit',e=>{e.preventDefault(); const p=loginPerson; const pass=document.getElementById('password-input').value.trim().toLowerCase(); if(pass!==FAMILY_PASSWORD){document.getElementById('login-error').textContent='That password doesn’t match the family one.';return} currentUser=p;switchingUser=false;localStorage.setItem(SESSION_KEY,p); currentView='lists'; commitDb(state=>{state.lastLogins[p]=new Date().toISOString();}); registerPresence();render();});
document.getElementById('toggle-password').addEventListener('click',()=>{const input=document.getElementById('password-input');input.type=input.type==='password'?'text':'password';});
document.querySelectorAll('.theme-toggle').forEach(button=>button.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='light'?'dark':'light')));
document.getElementById('change-user').addEventListener('click',()=>{switchingUser=true;loginPerson=currentUser;document.querySelectorAll('[data-person-choice]').forEach(choice=>choice.classList.toggle('selected',choice.dataset.personChoice===currentUser));document.getElementById('password-input').value='';document.getElementById('login-error').textContent='';render();});
function cancelUserSwitch(){if(!switchingUser)return;switchingUser=false;document.getElementById('password-input').value='';document.getElementById('login-error').textContent='';render();}
document.getElementById('cancel-user-switch').addEventListener('click',cancelUserSwitch);
document.getElementById('login-view').addEventListener('click',e=>{if(e.target===e.currentTarget&&switchingUser)cancelUserSwitch();});
document.getElementById('presence-widget').addEventListener('click',()=>{const panel=document.getElementById('login-history-panel');const widget=document.getElementById('presence-widget');const opening=panel.classList.contains('hidden');if(opening)renderLoginHistory();panel.classList.toggle('hidden',!opening);widget.setAttribute('aria-expanded',String(opening));});
document.addEventListener('click',e=>{const panel=document.getElementById('login-history-panel');const widget=document.getElementById('presence-widget');if(!panel.classList.contains('hidden')&&!panel.contains(e.target)&&!widget.contains(e.target))closeLoginHistory();});
document.getElementById('feature-button').addEventListener('click',()=>{renderFeatureRequests();document.getElementById('feature-dialog').showModal();});
function renderFeatureRequests(){
  const list=document.getElementById('feature-request-list');
  const requests=[...(db.featureRequests||[])].sort((a,b)=>(b.voters||[]).length-(a.voters||[]).length||new Date(b.createdAt)-new Date(a.createdAt));
  list.innerHTML=requests.length
    ? `<div class="feature-list-label">Family ideas</div>${requests.map(request=>{const voters=request.voters||[];const mine=request.by===currentUser;return `<div class="feature-request" data-feature-request="${request.id}"><div class="feature-request-copy"><div class="feature-request-display"><strong>${esc(request.text)}</strong><small>Suggested by ${esc(request.by)}${request.updatedAt?' · edited':''}</small>${mine?`<span class="feature-request-actions"><button type="button" data-edit-feature="${request.id}">Edit</button><button type="button" data-delete-feature="${request.id}">Delete</button></span>`:''}</div></div><button class="vote-button ${voters.includes(currentUser)?'voted':''}" data-vote="${request.id}">▲ <span>${voters.length}</span></button></div>`;}).join('')}`
    : '<div class="empty-features">No ideas yet — be the first.</div>';
  list.querySelectorAll('[data-vote]').forEach(button=>button.addEventListener('click',()=>{
    const requestId=button.dataset.vote;
    commitDb(state=>{const request=state.featureRequests.find(item=>item.id===requestId);if(!request)return false;if(!Array.isArray(request.voters))request.voters=[];const index=request.voters.indexOf(currentUser);if(index>=0)request.voters.splice(index,1);else request.voters.push(currentUser);});
  }));
  list.querySelectorAll('[data-edit-feature]').forEach(button=>button.addEventListener('click',()=>{const request=db.featureRequests.find(item=>item.id===button.dataset.editFeature&&item.by===currentUser);if(!request)return;editingFeatureId=request.id;document.getElementById('feature-input').value=request.text;document.getElementById('feature-dialog-title').textContent='Edit your feature';document.getElementById('feature-submit-button').innerHTML='Save changes <span>→</span>';document.getElementById('feature-input').focus();}));
  list.querySelectorAll('[data-delete-feature]').forEach(button=>button.addEventListener('click',()=>{pendingFeatureDelete=button.dataset.deleteFeature;document.getElementById('feature-delete-dialog').showModal();}));
}
function resetFeatureEditor(){editingFeatureId=null;document.getElementById('feature-input').value='';document.getElementById('feature-dialog-title').textContent='Suggest a feature';document.getElementById('feature-submit-button').innerHTML='Submit idea <span>→</span>';}
document.getElementById('feature-form').addEventListener('submit',e=>{e.preventDefault();const text=document.getElementById('feature-input').value.trim();if(!text)return;const requestId=editingFeatureId;const newRequestId=`feature-${Date.now()}`;const now=new Date().toISOString();commitDb(state=>{if(requestId){const request=state.featureRequests.find(item=>item.id===requestId&&item.by===currentUser);if(!request)return false;request.text=text;request.updatedAt=now;}else state.featureRequests.push({id:newRequestId,text,by:currentUser,createdAt:now,voters:[currentUser]});});resetFeatureEditor();});
document.getElementById('feature-dialog').addEventListener('close',resetFeatureEditor);
document.getElementById('chat-launcher').addEventListener('click',()=>{chatOpen=!chatOpen;document.getElementById('chat-panel').classList.toggle('hidden',!chatOpen);renderChat();if(chatOpen)document.getElementById('chat-input').focus();});
document.getElementById('chat-close').addEventListener('click',()=>{chatOpen=false;document.getElementById('chat-panel').classList.add('hidden');renderChat();});
document.getElementById('chat-expand').addEventListener('click',()=>{const panel=document.getElementById('chat-panel');panel.classList.toggle('expanded');document.getElementById('chat-expand').textContent=panel.classList.contains('expanded')?'↙':'↗';});
document.getElementById('chat-form').addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('chat-input');const text=input.value.trim();if(!text)return;const message={id:`message-${Date.now()}`,by:currentUser,text,createdAt:new Date().toISOString()};input.value='';commitDb(state=>{state.chatMessages.push(message);});input.focus();});
(function setupChatResize(){const handle=document.getElementById('chat-resize-handle');const panel=document.getElementById('chat-panel');let dragging=false,startX=0,startY=0,startW=0,startH=0;handle.addEventListener('pointerdown',e=>{dragging=true;startX=e.clientX;startY=e.clientY;const rect=panel.getBoundingClientRect();startW=rect.width;startH=rect.height;handle.setPointerCapture(e.pointerId);e.preventDefault();});handle.addEventListener('pointermove',e=>{if(!dragging)return;panel.style.width=`${Math.max(310,Math.min(window.innerWidth-32,startW+(startX-e.clientX)))}px`;panel.style.height=`${Math.max(340,Math.min(window.innerHeight-110,startH+(startY-e.clientY)))}px`;});handle.addEventListener('pointerup',()=>dragging=false);handle.addEventListener('pointercancel',()=>dragging=false);})();
document.getElementById('content').addEventListener('click',e=>{const update=e.target.closest('[data-update-person]');if(update){selectedPerson=update.dataset.updatePerson;currentView=selectedPerson===currentUser?'my-list':'person-list';render();}});
document.querySelectorAll('.nav-button').forEach(b=>b.addEventListener('click',()=>{currentView=b.dataset.view;selectedPerson=null;render();if(currentView==='giving')showGivingIntro();}));
document.getElementById('home-button').addEventListener('click',()=>{currentView='lists';selectedPerson=null;render();window.scrollTo({top:0,behavior:'smooth'});});
document.getElementById('item-form').addEventListener('submit',e=>{e.preventDefault();const values={name:document.getElementById('gift-input').value.trim(),priority:Number(document.getElementById('priority-input').value),cost:document.getElementById('cost-input').value.trim(),link:document.getElementById('link-input').value.trim(),notes:document.getElementById('notes-input').value.trim()};const editing=!!editItemId;const itemId=editItemId||`${currentUser}-${Date.now()}`;const now=new Date().toISOString();commitDb(state=>{if(editing){const item=state.lists[currentUser]?.find(entry=>entry.id===itemId);if(!item)return false;Object.assign(item,values,{updatedAt:now});}else state.lists[currentUser].push({...values,id:itemId,purchased:null,createdAt:now,createdBy:currentUser});});document.getElementById('item-dialog').close();resetItemDialog();});
document.querySelectorAll('.dialog-close').forEach(button=>button.addEventListener('click',e=>{e.preventDefault();button.closest('dialog').close();}));
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();}));
function renderBuyerChoices(){const container=document.getElementById('buyer-choices');container.innerHTML=PEOPLE.map(person=>`<button type="button" class="buyer-choice ${selectedBuyers.includes(person)?'selected':''}" data-buyer="${person}"><span>${person[0]}</span>${person}</button>`).join('');container.querySelectorAll('[data-buyer]').forEach(button=>button.addEventListener('click',()=>{const person=button.dataset.buyer;if(selectedBuyers.includes(person))selectedBuyers=selectedBuyers.filter(buyer=>buyer!==person);else selectedBuyers.push(person);document.getElementById('buyer-error').textContent='';renderBuyerChoices();}));}
function formatBuyerNames(buyers){if(buyers.length<2)return buyers[0]||'';if(buyers.length===2)return `${buyers[0]} & ${buyers[1]}`;return `${buyers.slice(0,-1).join(', ')} & ${buyers[buyers.length-1]}`;}
function openPurchase(id,person){purchaseGiftId=id;selectedPerson=person;selectedBuyers=[currentUser];const item=db.lists[person].find(x=>x.id===id);document.getElementById('purchase-gift-name').textContent=item.name;document.getElementById('buyer-error').textContent='';renderBuyerChoices();document.getElementById('claim-status-input').value='ordered';document.getElementById('order-date-input').value=new Date().toISOString().slice(0,10);document.getElementById('purchase-dialog').showModal();}
function openProgress(id,person){const item=db.lists[person].find(entry=>entry.id===id);if(!item?.purchased||!isMyPurchase(item))return;pendingProgress={id,person};document.getElementById('progress-gift-name').textContent=item.name;document.getElementById('progress-status-input').value=item.purchased.status||'ordered';document.getElementById('progress-dialog').showModal();}
function openUnclaim(id,person){pendingUnclaim={id,person};document.getElementById('unclaim-dialog').showModal();}
document.getElementById('cancel-unclaim').addEventListener('click',()=>document.getElementById('unclaim-dialog').close());
document.getElementById('cancel-delete').addEventListener('click',()=>{pendingDelete=null;document.getElementById('delete-dialog').close();});
document.getElementById('delete-form').addEventListener('submit',e=>{e.preventDefault();const itemId=pendingDelete;if(itemId)commitDb(state=>{const index=state.lists[currentUser]?.findIndex(item=>item.id===itemId)??-1;if(index<0)return false;state.lists[currentUser].splice(index,1);});pendingDelete=null;document.getElementById('delete-dialog').close();});
document.getElementById('cancel-comment-delete').addEventListener('click',()=>{pendingCommentDelete=null;document.getElementById('comment-delete-dialog').close();});
document.getElementById('comment-delete-form').addEventListener('submit',e=>{e.preventDefault();const pending=pendingCommentDelete;if(pending)commitDb(state=>{const item=state.lists[pending.person]?.find(entry=>entry.id===pending.itemId);const index=item?.comments?.findIndex(comment=>comment.id===pending.commentId&&comment.by===currentUser)??-1;if(index<0)return false;item.comments.splice(index,1);});pendingCommentDelete=null;document.getElementById('comment-delete-dialog').close();});
document.getElementById('cancel-feature-delete').addEventListener('click',()=>{pendingFeatureDelete=null;document.getElementById('feature-delete-dialog').close();});
document.getElementById('feature-delete-form').addEventListener('submit',e=>{e.preventDefault();const requestId=pendingFeatureDelete;if(requestId)commitDb(state=>{const index=state.featureRequests.findIndex(request=>request.id===requestId&&request.by===currentUser);if(index<0)return false;state.featureRequests.splice(index,1);});pendingFeatureDelete=null;resetFeatureEditor();document.getElementById('feature-delete-dialog').close();});
document.getElementById('unclaim-form').addEventListener('submit',e=>{e.preventDefault();const pending=pendingUnclaim;if(pending)commitDb(state=>{const item=state.lists[pending.person]?.find(x=>x.id===pending.id);if(!item?.purchased||!purchaseBuyers(item).includes(currentUser))return false;item.purchased=null;});pendingUnclaim=null;document.getElementById('unclaim-dialog').close();});
document.getElementById('progress-form').addEventListener('submit',e=>{e.preventDefault();const pending=pendingProgress;const status=document.getElementById('progress-status-input').value;const statusUpdatedAt=new Date().toISOString();if(pending)commitDb(state=>{const item=state.lists[pending.person]?.find(entry=>entry.id===pending.id);if(!item?.purchased||!purchaseBuyers(item).includes(currentUser))return false;item.purchased.status=status;item.purchased.statusUpdatedAt=statusUpdatedAt;});pendingProgress=null;document.getElementById('progress-dialog').close();});
document.getElementById('purchase-form').addEventListener('submit',e=>{e.preventDefault();if(!selectedBuyers.length){document.getElementById('buyer-error').textContent='Select at least one purchaser.';return;}const person=selectedPerson;const itemId=purchaseGiftId;const buyers=[...selectedBuyers];const purchase={by:formatBuyerNames(buyers),buyers,buyerIds:buyers,status:document.getElementById('claim-status-input').value,date:document.getElementById('order-date-input').value,arrival:document.getElementById('arrival-input').value.trim()};document.getElementById('purchase-dialog').close();commitDb(state=>{const item=state.lists[person]?.find(x=>x.id===itemId);if(!item||item.purchased)return false;item.purchased=purchase;}).then(result=>{if(result&&!result.committed){document.getElementById('buyer-error').textContent='Someone else just claimed this gift. The list has been refreshed.';document.getElementById('purchase-dialog').showModal();}});});
render();
renderChat();
setupFirebase();
setInterval(()=>{if(currentUser)renderCountdown();},60000);
